import { Food } from "./food.model";

export const mockFood: Food[] = [
  { id: 11, unit: '1 кусок', name: 'Белый хлеб', amount: '20 г', value: 1 }, 
  { id: 12, unit: '1 кусок', name: 'Черный хлеб', amount: '25 г', value: 1 }, 
  { id: 13, unit: '', name: 'Сухари', amount: '15 г', value: 1 }, 
  { id: 14, unit: '', name: 'Крекеры', amount: '15 г', value: 1 }, 
  { id: 15, unit: '1 ст. ложка', name: 'Панировочные сухари', amount: '15 г', value: 1 }, 

  { id: 21, unit: '1 - 2 ст. ложка', name: 'Вермишель', amount: '15 г', value: 1 }, 
  { id: 22, unit: '1 - 2 ст. ложка', name: 'Лапша', amount: '15 г', value: 1 }, 
  { id: 23, unit: '1 - 2 ст. ложка', name: 'Рожки', amount: '15 г', value: 1 }, 
  { id: 24, unit: '1 - 2 ст. ложка', name: 'Макароны', amount: '15 г', value: 1 }, 

  { id: 31, unit: '1 ст. ложка', name: 'Гречневая', amount: '15 г', value: 1 }, 
  { id: 32, unit: '1/2 початка, среднего', name: 'Кукуруза', amount: '100 г', value: 1 }, 
  { id: 33, unit: '3 ст. ложки', name: 'Кукуруза консервированная', amount: '60 г', value: 1 }, 
  { id: 34, unit: '4 ст. ложки', name: 'Кукурузные хлопья', amount: '15 г', value: 1 }, 
  { id: 35, unit: '10 ст. ложек', name: 'Попкорн', amount: '15 г', value: 1 }, 
  { id: 36, unit: '1 ст. ложка', name: 'Манная', amount: '15 г', value: 1 }, 
  { id: 37, unit: '1 ст. ложка', name: 'Мука', amount: '15 г', value: 1 }, 
  { id: 38, unit: '1 ст. ложка', name: 'Овсяная', amount: '15 г', value: 1 }, 
  { id: 39, unit: '2 ст. ложки', name: 'Овсяные хлопья', amount: '20 г', value: 1 }, 
  { id: 310, unit: '1 ст. ложка', name: 'Перловая', amount: '15 г', value: 1 }, 
  { id: 311, unit: '1 ст. ложка', name: 'Пшено', amount: '15 г', value: 1 }, 
  { id: 312, unit: '1 ст. ложка', name: 'Рис', amount: '15 г', value: 1 }, 

  { id: 41, unit: '1 штука, средняя', name: 'Картофель сырой и вареный', amount: '75 г', value: 1 }, 
  { id: 42, unit: '2 ст. ложки', name: 'Картофельное пюре', amount: '90 г', value: 1 }, 
  { id: 43, unit: '2 ст. ложки', name: 'Жареный картофель', amount: '35 г', value: 1 }, 
  { id: 44, unit: '', name: 'Сухой картофель (чипсы)', amount: '25 г', value: 1 }, 

  { id: 51, unit: '1 стакан', name: 'Молоко', amount: '250 мл', value: 1 }, 
  { id: 52, unit: '1 стакан', name: 'Кефир', amount: '250 мл', value: 1 }, 
  { id: 53, unit: '1 стакан', name: 'Сливки', amount: '250 мл', value: 1 }, 
  { id: 54, unit: '', name: 'Йогурт натуральный', amount: '200 г', value: 1 }, 

  { id: 61, unit: '2-3 штуки', name: 'Абрикосы', amount: '110 г', value: 1 }, 
  { id: 62, unit: '1 штука крупная', name: 'Айва', amount: '140 г', value: 1 }, 
  { id: 63, unit: '1 кусок (поперечный срез)', name: 'Ананас', amount: '140 г', value: 1 }, 
  { id: 64, unit: '1 кусок', name: 'Арбуз', amount: '270 г', value: 1 }, 
  { id: 65, unit: '1 штука, средний', name: 'Апельсин', amount: '150 г', value: 1 }, 
  { id: 66, unit: '1/2 штуки, среднего', name: 'Банан', amount: '70 г', value: 1 }, 
  { id: 67, unit: '7 ст. ложек', name: 'Брусника', amount: '140 г', value: 1 }, 
  { id: 68, unit: '12 штук, небольших', name: 'Виноград', amount: '70 г', value: 1 }, 
  { id: 69, unit: '15 штук', name: 'Вишня', amount: '90 г', value: 1 }, 
  { id: 610, unit: '1 штука, средний', name: 'Гранат', amount: '170 г', value: 1 }, 
  { id: 611, unit: '1/2 штуки, крупного', name: 'Грейпфрукт', amount: '170 г', value: 1 }, 
  { id: 612, unit: '1 штука, маленькая', name: 'Груша', amount: '90 г', value: 1 }, 
  { id: 613, unit: '1 кусок', name: 'Дыня', amount: '100 г', value: 1 }, 
  { id: 614, unit: '8 ст. ложек', name: 'Ежевика', amount: '140 г', value: 1 }, 
  { id: 615, unit: '1 штука', name: 'Инжир', amount: '80 г', value: 1 }, 
  { id: 616, unit: '1 штука, крупный', name: 'Киви', amount: '110 г', value: 1 }, 
  { id: 617, unit: '10 штук, средний', name: 'Клубника', amount: '160 г', value: 1 }, 
  { id: 618, unit: '6 ст. ложек', name: 'Крыжовник', amount: '120 г', value: 1 }, 
  { id: 619, unit: '8 ст. ложек', name: 'Малина', amount: '160 г', value: 1 }, 
  { id: 620, unit: '1/2 штуки, небольшого', name: 'Манго', amount: '110 г', value: 1 }, 
  { id: 621, unit: '2-3 штуки, средних', name: 'Мандарины', amount: '150 г', value: 1 }, 
  { id: 622, unit: '1 штука, средний', name: 'Персик', amount: '120 г', value: 1 }, 
  { id: 623, unit: '3-4 штуки, небольших', name: 'Сливы', amount: '90 г', value: 1 }, 
  { id: 624, unit: '7 ст. ложек', name: 'Смородина', amount: '120 г', value: 1 }, 
  { id: 625, unit: '1/2 штуки, средней', name: 'Хурма', amount: '70 г', value: 1 }, 
  { id: 626, unit: '7 ст. ложек', name: 'Черника', amount: '90 г', value: 1 }, 
  { id: 627, unit: '1 штука, маленькое', name: 'Яблоко', amount: '90 г', value: 1 }, 
  { id: 628, unit: '1/2 стакана', name: 'Фруктовый сок', amount: '100 мл', value: 1 }, 
  { id: 629, unit: '', name: 'Сухофрукты', amount: '20 г', value: 1 }, 

  { id: 71, unit: '3 штуки, средних', name: 'Морковь', amount: '200 г', value: 1 }, 
  { id: 72, unit: '1 штука, средняя', name: 'Свекла', amount: '150 г', value: 1 }, 
  { id: 73, unit: '1 ст. ложка, сухих', name: 'Бобы', amount: '20 г', value: 1 }, 
  { id: 74, unit: '7 ст. ложек, свежего', name: 'Горох', amount: '100 г', value: 1 }, 
  { id: 75, unit: '3 ст. ложки, вареной', name: 'Фасоль', amount: '50 г', value: 1 }, 
  { id: 76, unit: '', name: 'Орехи', amount: '60-90 г', value: 1 }, 

  { id: 81, unit: '2 ч. ложки', name: 'Сахар-песок', amount: '10 г', value: 1 }, 
  { id: 82, unit: '2 куска', name: 'Сахар кусковой', amount: '10 г', value: 1 }, 
  { id: 83, unit: '1/2 стакана', name: 'Газированная вода на сахаре', amount: '100 мл', value: 1 }, 
  { id: 84, unit: '1 стакан', name: 'Квас', amount: '250 мл', value: 1 }, 
  { id: 85, unit: '', name: 'Мороженое', amount: '65 г', value: 1 }, 
  { id: 86, unit: '', name: 'Шоколад', amount: '20 г', value: 1 }, 
  { id: 87, unit: '', name: 'Мед', amount: '12 г', value: 1 }, 
]